# Generated by Django 5.2 on 2025-04-15 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="District",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{5}$", "Enter a valid 5-digit postal code"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_1",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
