# Generated by Django 5.2 on 2025-04-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_location_postal_code_location_zip_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
            ),
        ),
    ]
