# Generated by Django 5.2 on 2025-04-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_location_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="District",
            field=models.CharField(
                choices=[
                    ("jhapa", "Jhapa"),
                    ("morang", "Morang"),
                    ("sunsari", "Sunsari"),
                    ("kathmandu", "Kathmandu"),
                    ("lalitpur", "Lalitpur"),
                    ("bhaktapur", "Bhaktapur"),
                    ("chitwan", "Chitwan"),
                    ("pokhara", "Pokhara"),
                    ("dhanusha", "Dhanusha"),
                    ("rupandehi", "Rupandehi"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="Zip_Code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
