# Generated by Django 5.2 on 2025-04-19 02:15

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_location_district_alter_location_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_photo/default.png",
                null=True,
                upload_to=users.utils.user_directory_path,
            ),
        ),
    ]
