# Generated by Django 5.2 on 2025-04-19 02:45

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=users.utils.user_directory_path
            ),
        ),
    ]
