# Generated by Django 5.2 on 2025-04-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Location",
            new_name="location",
        ),
    ]
