# Generated by Django 5.2 on 2025-04-21 08:42

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_location_profile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.utils.user_directory_path
            ),
        ),
    ]
