# Generated by Django 5.2 on 2025-04-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_listing_brans_listing_color_listing_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="color",
            field=models.CharField(max_length=24),
        ),
    ]
