# Generated by Django 5.2 on 2025-04-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_listing_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="brans",
            field=models.CharField(
                choices=[
                    ("hyundai", "Hyundai"),
                    ("suzuki", "Suzuki"),
                    ("kia", "Kia"),
                    ("tata", "Tata"),
                    ("mahindra", "Mahindra"),
                    ("toyota", "Toyota"),
                    ("nissan", "Nissan"),
                    ("honda", "Honda"),
                    ("ford", "Ford"),
                    ("renault", "Renault"),
                    ("volkswagen", "Volkswagen"),
                    ("isuzu", "Isuzu"),
                    ("mitsubishi", "Mitsubishi"),
                    ("chevrolet", "Chevrolet"),
                    ("dfsk", "DFSK"),
                    ("great wall", "Great Wall"),
                    ("mg", "MG"),
                    ("baic", "BAIC"),
                    ("peugeot", "Peugeot"),
                    ("chery", "Chery"),
                    ("geely", "Geely"),
                    ("byd", "BYD"),
                ],
                default=None,
                max_length=24,
            ),
        ),
    ]
