# Generated by Django 5.2 on 2025-04-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_listing_brans"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="brans",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="milage",
            new_name="mileage",
        ),
    ]
